name: Modelica Tests

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          cache-suffix: "uv"
          cache-dependency-glob: requirements.txt

      - name: Create and Activate Virtual Environment
        run: |
          uv venv test-env
          source test-env/bin/activate
          echo $VIRTUAL_ENV

      - name: Setup test environment
        id: setup-env
        run: |
          source test-env/bin/activate
          echo $VIRTUAL_ENV
          uv pip install -r requirements.txt

      - name: Pull OMPython Docker Image
        # https://openmodelica.org/download/docker/
        run: docker pull openmodelica/openmodelica:v1.24.4-ompython

      - name: Check docker image
        run: |
          echo "HOME=$HOME" && \
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE" && \
          docker run --rm \
            --volume "$HOME:${{ github.workspace }}" \
            --env "HOME=${{ github.workspace }}" \
            --workdir "$PWD" \
            --user $UID \
            openmodelica/openmodelica:v1.24.4-ompython \
            pwd && \
          docker run --rm \
            --volume "$HOME:${{ github.workspace }}" \
            --env "HOME=${{ github.workspace }}" \
            --workdir "$PWD" \
            --user $UID \
            openmodelica/openmodelica:v1.24.4-ompython \
            ls -rl *

      - name: Test running OMPython of docker image
        run: |
          . test-env/bin/activate && \
          python -m pytest \
            --json-report --json-report-indent=4 --json-report-file="test_OMPython.json" \
            tests/test__docker_run_pytest_ompython.py

      - name: Test running pytest within the OMPython docker image
        run: 'docker run --rm --volume "$HOME:${{ github.workspace }}" --env "HOME=${{ github.workspace }}" --workdir "$PWD" --user $UID openmodelica/openmodelica:v1.24.4-ompython python -m pytest tests/test__check_ompython.py'

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test_*.json

  ai-tutor:
    runs-on: ubuntu-latest
    needs: build-test
    if: ${{ always() }}
    strategy:
      fail-fast: true # set `false` for all languages
      max-parallel: 1 # to save CI time
      matrix:
        language: [English, Korean, "Bahasa Indonesia", Chinese, French, German, Italian, Japanese, Nederlands, Norwegian, Spanish, Swedish, Thai, Vietnamese]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-report

      - name: AI Tutor
        uses: docker://ghcr.io/kangwonlee/gemini-python-tutor:latest
        id: ai-tutor
        with:
          report-files: test_OMPython.json
          student-files: check_ompython.py
          readme-path: README.md
          api-key: ${{ secrets.GOOGLE_API_KEY }}
          explanation-in: ${{ matrix.language }}
        if: always()
        timeout-minutes: 2
