name: Modelica Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install OpenModelica
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates curl gnupg lsb-release
          sudo curl -fsSL https://build.openmodelica.org/apt/openmodelica.asc | sudo gpg --dearmor -o /usr/share/keyrings/openmodelica.gpg

          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/openmodelica.gpg] https://build.openmodelica.org/apt $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/openmodelica.list

          sudo apt-get update
          sudo apt-get install --no-install-recommends omc # no graphical clients

      - name: Export FMU
        run: |
          which omc
          omc --version
          omc exportFMU.mos
          ls -l
          ls -rl models/

      - name: Set up Miniconda and create test environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          activate-environment: test-environment
          environment-file: tests/environment.yml
  
      - name: Run Tests and Generate Report
        run: |
          conda init
          conda activate test-environment
          conda list
          pytest --json-report --json-report-indent=4 --json-report-file=test_report.json tests/test_vibrating_system.py
        shell: bash -el {0}

      - name: AI Tutor in English
        uses: kangwonlee/gemini-python-tutor@main
        with:
          report-files: test_report.json
          student-files: models/package1/modelA.mo,exportFMU.mos
          readme-path: README.md
          api-key: ${{ secrets.GOOGLE_API_KEY }}
          explanation-in: English
        id: ai-tutor-English
        if: always()
        timeout-minutes: 2

      - name: AI Tutor in Swedish
        uses: kangwonlee/gemini-python-tutor@main
        with:
          report-files: test_report.json
          student-files: models/package1/modelA.mo,exportFMU.mos
          readme-path: README.md
          api-key: ${{ secrets.GOOGLE_API_KEY }}
          explanation-in: Swedish
        id: ai-tutor-Swedish
        if: always()
        timeout-minutes: 2

      - name: AI Tutor in German
        uses: kangwonlee/gemini-python-tutor@main
        with:
          report-files: test_report.json
          student-files: models/package1/modelA.mo,exportFMU.mos
          readme-path: README.md
          api-key: ${{ secrets.GOOGLE_API_KEY }}
          explanation-in: German
        id: ai-tutor-German
        if: always()
        timeout-minutes: 2

      - name: AI Tutor in Korean
        uses: kangwonlee/gemini-python-tutor@main
        with:
          report-files: test_report.json
          student-files: models/package1/modelA.mo,exportFMU.mos
          readme-path: README.md
          api-key: ${{ secrets.GOOGLE_API_KEY }}
          explanation-in: Korean
        id: ai-tutor-Korean
        if: always()
        timeout-minutes: 2

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test_report.json
