name: Modelica Tests

on: [push, pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull Docker Image
        # https://openmodelica.org/download/docker/
        run: docker pull openmodelica/openmodelica:v1.24.4-ompython

      - name: Run OpenModelica
        run: 'docker run --rm --volume "$HOME:${{ github.workspace }}" --env "HOME=${{ github.workspace }}" --workdir "$PWD" --user $UID openmodelica/openmodelica:v1.24.4-ompython python -m pytest tests/test__check_ompython.py'

      - name: Run Tests and Generate Report
        run: |
          conda init
          conda activate test-environment
          conda list
          pytest --json-report --json-report-indent=4 --json-report-file=test_report.json tests/test_vibrating_system.py
        shell: bash -el {0}

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: test_report.json

  ai-tutor:
    runs-on: ubuntu-latest
    needs: build-test
    if: ${{ always() }}
    strategy:
      fail-fast: true # set `false` for all languages
      max-parallel: 1 # to save CI time
      matrix:
        language: [English, Korean, "Bahasa Indonesia", Chinese, French, German, Italian, Japanese, Nederlands, Norwegian, Spanish, Swedish, Thai, Vietnamese]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: test-report

      - name: AI Tutor
        uses: docker://ghcr.io/kangwonlee/gemini-python-tutor:latest
        id: ai-tutor
        with:
          report-files: test_report.json
          student-files: models/package1/modelA.mo,exportFMU.mos
          readme-path: README.md
          api-key: ${{ secrets.GOOGLE_API_KEY }}
          explanation-in: ${{ matrix.language }}
        if: always()
        timeout-minutes: 2
